name: 'Terraform Azure Deployment'

on:
  push:
    branches: [ main ]

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest

    steps:
    # Step 1: Checkout code
    - name: Checkout code
      uses: actions/checkout@v4

    # Step 2: Generate SSH Key Pair
    - name: Generate SSH Key
      run: |
        mkdir -p ~/.ssh
        ssh-keygen -t rsa -b 4096 -f ~/.ssh/id_rsa -q -N ""
        echo "SSH Public Key:"
        cat ~/.ssh/id_rsa.pub

    # Step 3: Setup Terraform
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v3
      with:
        terraform_version: 1.5.0

    # Step 4: Terraform Format Check
    - name: Terraform Format
      run: terraform fmt -check -recursive

    # Step 5: Terraform Init
    - name: Terraform Init
      run: terraform init

    # Step 6: Terraform Validate
    - name: Terraform Validate
      run: terraform validate -no-color

    # Step 7: Terraform Plan
    - name: Terraform Plan
      run: terraform plan -var-file="azure_credentials.tfvars" -no-color -input=false

    # Step 8: Terraform Apply
    - name: Terraform Apply
      run: terraform apply -var-file="azure_credentials.tfvars" -auto-approve -input=false

    # Step 9: Output deployment information
    - name: Show Outputs
      run: terraform output

    # Step 10: Save SSH Private Key (optional - for debugging)
    - name: Save SSH Private Key
      if: always()
      run: |
        echo "SSH Private Key (save this to connect to VMs):"
        cat ~/.ssh/id_rsa
      shell: bash